### ISSUE TITLE
Feature request: Ability to change "You" to Your Character Name

### ISSUE THREAD

**Issue by KingCruzIII** [hibiyasleep/kagerou#100]
Not a big feature, but it would be nice to be able to change the "YOU" in the name column to my character name.

**Comment by hibiyasleep** [comment]
![image](https://user-images.githubusercontent.com/5380174/44361163-035be980-a4f8-11e8-85db-90b77a8445d0.png)
it's here in ACT Options, make sure set your name in settings after configure this.

**Comment by ChalkPE** [comment]
Here's alternative without changing any ACT options
paste below code to  **kagerou config -> More > CSS** and click **Save**.

```css
#table li.me .flex-column-i-name { font-size: 0; }
#table li.me .flex-column-i-name::before { font-size: 12px; content: 'Your Custom Name'; }
```

![image](https://user-images.githubusercontent.com/9481405/131971372-50e7f83f-d421-4e89-a179-829b8bb5389f.png)
