### ISSUE TITLE
Is it possible to make kagerou expand upward instead of down?

### ISSUE THREAD

**Issue by altissia86** [hibiyasleep/kagerou#108]
I am currently rearranging my hud and planning to place my overlay at the bottom right of my screen.
1. Is there a way to make it expand upward? Currently it will expand downward and i cant see anything.
2. This is pretty minor but please make collapsed state is saved when I close my ACT.

**Comment by hibiyasleep** [comment]
1) Yep, possible with some CSS; paste this into `Settings > More > CSS`.

```css

body {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}
body.overlay {
  margin-top: 0 !important;
  margin-bottom: 0.5rem !important;
}
main {
  order: 0;
}
nav {
  order: 1;
}
#header {
  top: 1.5rem;
}
footer {
  top: 0;
  bottom: unset;
}
#table {
  padding-top: 1.5rem;
  padding-bottom: 0;
}
.collapsed #table {
  margin-top: 1.5rem;
  padding-top: 0;
}
```

2) Sure, I'll include it in next update.
