### ISSUE TITLE
CSS 

### ISSUE THREAD

**Issue by ccf18** [hibiyasleep/kagerou#150]
Hi, thanks for the great overlay. Sorry that I don't know where else to post this.  Could you please advise if I can change the color of the scrollbar or even disable the scrollbar? Setting main > ul to overflow-y:hidden doesn't work. Please advise.. thanks alot

**Comment by hibiyasleep** [comment]
as seen [here](https://github.com/hibiyasleep/kagerou/blob/master/overlay/css/index.css#L100), you should specify `::webkit-scrollbar-*`.

so
```css
::-webkit-scrollbar-thumb {
  background: rgba(255, 0, 0, 0.25);
}
```
this will recolor scrollbar as transparent red,

```css
::-webkit-scrollbar {
  display: none;
}
```

will completely hide scrollbar itself (visually).
