### ISSUE TITLE
Add rank # to name (feature request)

### ISSUE THREAD

**Issue by brentrichardjr** [hibiyasleep/kagerou#175]
Any chance to get an option to add the rank # displayed in front of the names?

If there is an easy way to add this via CSS, I can do that as well. Thank you

**Comment by ChalkPE** [comment]
You can use [CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters)

```css
#table {
  counter-reset: rank;
}

#table .flex-column-i-name::before {
  counter-increment: rank;
  content: "#" counter(rank) " ";
}
```

![image](https://user-images.githubusercontent.com/9481405/132458436-6927a449-e399-47c3-8b88-93ad4256c92d.png)
