### ISSUE TITLE
Option for hide resize handle

### ISSUE THREAD

**Issue by hibiyasleep** [hibiyasleep/kagerou#41]
```css
body::after { display: none }
```

Plans:
* Add a `remove-handle` class to body, which is simple but dirty.
* Split out `<span class="handle" />`, which cannot migrated from CSS-based hiding.
