### ISSUE TITLE
Change Collapse Method

### ISSUE THREAD

**Issue by Griever92** [hibiyasleep/kagerou#57]
Is it possible to have the parser window collapse from top to bottom, instead of bottom to top?

**Comment by hibiyasleep** [comment]
Currently not possible even with CSS, since `collapsed` flag class applied to `<main>`. I'll make this able to work with CSS.

**Comment by hibiyasleep** [comment]
Issue for resolution at #58.

**Comment by hibiyasleep** [comment]
This is now possible by 9b390940d4750b6bdc80996a393b8934a55c69fc - add this:

```css
body {
  display: flex;
  flex-direction: column;
  justify-content: flex-end;
}
```
